debug: false

language: 'id' # 'id' for Indonesian, 'en' for English

mythicmobs:
  spesifik_mob:
    SkeletonWarrior:
      nama_mobs:
        - 'SkeletonKing'
        - 'SkeletalMinion'
      maks:
        - '1'
        - '2'
    SkeletalKnight:
      nama_mob:
        - 'SkeletalKnight'
      mak:
        - '1'
    Zombies:
      nama_mobs:
        - 'HUSK'
        - 'Zombie'
      maks:
        - '-1'
        - '3'

jadwal-reset:
  reset1:
    enabled: false
    type: 'id'
    resource:
      id: 'SkeletonWarrior'
      hari: 'senin'
      waktu: '00:00'
      s-m-h: '-1'
      interval: 'mingguan'
      respawn: 'true'
      loc: 'world:100,64,100'
  reset2:
    enabled: true
    type: 'mob'
    resource:
      mob: 'SkeletalKnight'
      hari: '-1'
      waktu: '-1'
      s-m-h: '500s'
      interval: 'detik'
      respawn: 'true'
      loc: 'world:100,64,100'
  reset3:
    enabled: false
    type: 'id'
    resource:
      id: 'Zombies'
      hari: 'minggu'
      waktu: '23:59'
      s-m-h: '-1'
      interval: 'bulanan'
      respawn: 'false'
      loc: 'none'
