name: MMTracker
version: '1.0'
main: net.justforfun.MMTracker.Main
api-version: '1.20'
depend: [MythicMobs, PlaceholderAPI]

commands:
  mmtracker:
    description: MMTracker command
    usage: /mmtracker <reload|reset>
    permission: mmtracker.use

permissions:
  mmtracker.use:
    description: Permission to use MMTracker commands
    default: op
